# Copyright 2010 - 2012, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

Import('env')

test_env = env.Clone()
test_env.Append(CPPPATH = test_env.Dir('..').srcnode())

if test_env['OS'] != 'win8':
    # Test Programs
    progs = [
        test_env.Program('bastress',      ['bastress.cc']),
        test_env.Program('bastress2',     ['bastress2.cc']),
        test_env.Program('bignum',        ['bignum.cc']),
        test_env.Program('socktest',      ['socktest.cc']),
        test_env.Program('autochat',      ['autochat.cc']),
        test_env.Program('remarshal',     ['remarshal.cc']),
        test_env.Program('unpack',        ['unpack.cc']),
        test_env.Program('rsa',           ['rsa.cc']),
        test_env.Program('srp',           ['srp.cc']),
        test_env.Program('aes_ccm',       ['aes_ccm.cc']),
        test_env.Program('keystore',      ['keystore.cc']),
        test_env.Program('bbservice',     ['bbservice.cc']),
        test_env.Program('bbsig',         ['bbsig.cc']),
        test_env.Program('bbclient',      ['bbclient.cc']),
        test_env.Program('bbjoin',        ['bbjoin.cc']),
        test_env.Program('bbjitter',      ['bbjitter.cc']),
        test_env.Program('bttimingclient', ['bttimingclient.cc']),
        test_env.Program('marshal',       ['marshal.cc']),
        test_env.Program('names',         ['names.cc']),
        test_env.Program('compression',   ['compression.cc']),
        test_env.Program('rawclient',     ['rawclient.cc']),
        test_env.Program('rawservice',    ['rawservice.cc']),
        test_env.Program('sessions',      ['sessions.cc']),
        test_env.Program('ledctrl',       ['ledctrl.cc'])
        ]

    if test_env['OS'] == 'linux' or test_env['OS'] == 'android':
        progs.extend(test_env.Program('mc-rcv',     ['mc-rcv.cc']))
        progs.extend(test_env.Program('mc-snd',     ['mc-snd.cc']))
        progs.extend(test_env.Program('bluetoothd-crasher',     ['bluetoothd-crasher.cc']))

    if test_env['OS'] == 'win7':
        progs.extend(test_env.Program('mouseclient', ['mouseclient.cc']))
        progs.extend(test_env.Program('litegen',     ['litegen.cc']))

    Return('progs')
    
# win8    
progs=[]    
Return('progs')
