# Copyright 2010 - 2013, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

Import('env')

# Install sample source
clientDistDir = '$CPP_DISTDIR/samples/chat'
if env['OS'] == 'android':
    env.Install(clientDistDir, 'android/AndroidManifest.xml')
    env.Install(clientDistDir, 'android/.classpath')
    env.Install(clientDistDir, 'android/.project')
    env.Install(clientDistDir, 'android/default.properties')
    env.Install(clientDistDir, env.Dir('android/jni').srcnode())
    env.Install(clientDistDir, env.Dir('android/src').srcnode())
    env.Install(clientDistDir, env.Dir('android/res').srcnode())

elif env['OS'] in ['linux', 'darwin']:
    env.Program('chat', ['linux/chat.cc'])
    env.Install('$CPP_DISTDIR/bin/samples', ['chat'])
    env.Install(clientDistDir, env.Glob('linux/*.cc'))
    env.Install(clientDistDir, env.Glob('linux/Make*'))

elif env['OS_GROUP'] == 'windows':
    env.Program('chat', ['linux/chat.cc'])
    env.Install('$CPP_DISTDIR/bin/samples', ['chat.exe'])
    env.Install(clientDistDir, env.Glob('linux/*.cc'))
    #install Visual Studio solution files
    env.Install(clientDistDir+'/VC2008Win7', 'linux/VC2008Win7/VC2008Win7.sln')
    env.Install(clientDistDir+'/VC2008Win7/chatsample', 'linux/VC2008Win7/chatsample/chatsample.vcproj')
