# Copyright 2013 Qualcomm Innovation Center, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

Import('env')
clientDistDir = '$DISTDIR/cpp/samples/SampleDaemon'

# Program binary
prog = [ env.Program('SampleDaemon', 'SampleDaemon.cc') ]

# The sample daemon binary is intended to be used by thin client apps and is
# packaged with ThinClient SDK (Win7/Linux). It sets credentials so that
# the thin client apps connect to it in a trusted manner (meaning: requires BD)

if env['BD'] == 'on' and env['OS'] in ['linux', 'win7']:
    env.Install('$DISTDIR/cpp/bin/samples', prog )
    env.Install(clientDistDir, env.Glob('*.cc'))
