# Copyright 2011-2013, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

Import('env')

# Install source
if env['OS'] == 'android':
    distDir = '$CPP_DISTDIR/alljoyn_android/bundle_test/BundledClient'
    env.Install(distDir, 'bundle_test/BundledClient/AndroidManifest.xml')
    env.Install(distDir, 'bundle_test/BundledClient/.classpath')
    env.Install(distDir, 'bundle_test/BundledClient/.project')
    env.Install(distDir, 'bundle_test/BundledClient/project.properties')
    env.Install(distDir, env.Dir('bundle_test/BundledClient/src').srcnode())
    env.Install(distDir, env.Dir('bundle_test/BundledClient/res').srcnode())

    distDir = '$CPP_DISTDIR/alljoyn_android/bundle_test/BundledService'
    env.Install(distDir, 'bundle_test/BundledService/AndroidManifest.xml')
    env.Install(distDir, 'bundle_test/BundledService/.classpath')
    env.Install(distDir, 'bundle_test/BundledService/.project')
    env.Install(distDir, 'bundle_test/BundledService/project.properties')
    env.Install(distDir, env.Dir('bundle_test/BundledService/src').srcnode())
    env.Install(distDir, env.Dir('bundle_test/BundledService/res').srcnode())
    
    distDir = '$CPP_DISTDIR/alljoyn_android/alljoyn_android_ext'
    env.Install(distDir, 'alljoyn_android_ext/AndroidManifest.xml')
    env.Install(distDir, 'alljoyn_android_ext/.classpath')
    env.Install(distDir, 'alljoyn_android_ext/.project')
    env.Install(distDir, 'alljoyn_android_ext/default.properties')
    env.Install(distDir, env.Dir('alljoyn_android_ext/jni').srcnode())
    env.Install(distDir, env.Dir('alljoyn_android_ext/src').srcnode())
    env.Install(distDir, env.Dir('alljoyn_android_ext/res').srcnode())
    
#    distDir = '$CPP_DISTDIR/alljoyn_android/alljoyn_android_p2pservice'
#    env.Install(distDir, 'alljoyn_android_p2pservice/AndroidManifest.xml')
#    env.Install(distDir, 'alljoyn_android_p2pservice/.classpath')
#    env.Install(distDir, 'alljoyn_android_p2pservice/.project')
#    env.Install(distDir, 'alljoyn_android_p2pservice/default.properties')
#    env.Install(distDir, env.Dir('alljoyn_android_p2pservice/jni').srcnode())
#    env.Install(distDir, env.Dir('alljoyn_android_p2pservice/src').srcnode())
#    env.Install(distDir, env.Dir('alljoyn_android_p2pservice/res').srcnode())
    
    distDir = '$CPP_DISTDIR/alljoyn_android/ice_client_login_service'
    env.Install(distDir, 'ice_client_login_service/AndroidManifest.xml')
    env.Install(distDir, 'ice_client_login_service/.classpath')
    env.Install(distDir, 'ice_client_login_service/.project')
    env.Install(distDir, 'ice_client_login_service/default.properties')
    env.Install(distDir, env.Dir('ice_client_login_service/src').srcnode())
    env.Install(distDir, env.Dir('ice_client_login_service/res').srcnode())
