# Copyright 2013, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 


Import('daemon_env')

bt_env = daemon_env.Clone()

bt_env.Append(CPPPATH=[bt_env.Dir('.').srcnode()])

objs = bt_env.Object(bt_env.Glob('*.cc'))

if bt_env['OS'] in ['linux', 'openwrt', 'android']:
    objs.extend(bt_env.SConscript('bt_bluez/SConscript', exports = ['bt_env']))

Return('objs')
