# Copyright 2010 - 2013, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

import os
Import('daemon_env', 'daemon_objs')

# Add OS specific daemon_objs
if daemon_env['ICE'] == 'on':
    os_objs = daemon_env.Object(['ProximityScanner.cc', 'Socket.cc'])
else:
    os_objs = []

proximity_objs = daemon_env.SConscript('proximity/SConscript', exports = ['daemon_env'])
winmdswitch = '\"/WINMDFILE:%s\"' % os.path.abspath('AllJoyn.winmd')
daemon_env.Append(LINKFLAGS=['/MANIFEST:NO', '/SUBSYSTEM:CONSOLE', '/TLBID:1', '/APPCONTAINER', '/WINMD', winmdswitch])

if daemon_env['CPU'] == 'arm':
    daemon_env.Append(LINKFLAGS=['/INCREMENTAL:NO'])

# Build the resources for the dll
rsc = daemon_env.RES('DaemonResources.rc')

# Build the Windows daemon.
alljoyn_libs = daemon_env.SharedLibrary('AllJoyn', daemon_objs + proximity_objs + os_objs)
daemon_env.Install('$WINRT_DISTDIR/bin', 'AllJoyn.winmd') #put the *.winmd file in the bin folder

progs = [alljoyn_libs] # alljoyn.dll will be returned
Return('progs', 'os_objs')
